# Generated by Django 5.0.6 on 2024-06-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='overall',
        ),
    ]
