# Generated by Django 5.0.6 on 2024-06-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_remove_student_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='art',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='econ',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='lit',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='math',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='music',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='science',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='ss',
            field=models.IntegerField(default=500),
        ),
    ]
