# Generated by Django 5.0.6 on 2024-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0007_student_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='name', max_length=64),
        ),
    ]
