# Generated by Django 5.0.6 on 2024-06-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='name', max_length=64),
        ),
    ]
