# Generated by Django 5.0.6 on 2024-06-15 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_alter_student_art_alter_student_econ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=64)),
                ('ss', models.IntegerField(blank=True, default=None)),
                ('lit', models.IntegerField(blank=True, default=None)),
                ('econ', models.IntegerField(blank=True, default=None)),
                ('math', models.IntegerField(blank=True, default=None)),
                ('science', models.IntegerField(blank=True, default=None)),
                ('music', models.IntegerField(blank=True, default=None)),
                ('art', models.IntegerField(blank=True, default=None)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.aevent')),
            ],
        ),
    ]
