# Generated by Django 5.0.6 on 2024-06-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_aevent_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='art',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='econ',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='lit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='math',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='music',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='science',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='ss',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
