# Generated by Django 5.0.6 on 2024-06-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_alter_input_art_alter_input_econ_alter_input_lit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.CharField(choices=[('Honors', 'Honors'), ('Scholastic', 'Scholastic'), ('Varsity', 'Varsity')], default='Honors', max_length=64),
        ),
    ]
