# Generated by Django 5.0.6 on 2024-06-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_student_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Full_name', max_length=64),
        ),
    ]
