# Generated by Django 5.0.6 on 2024-09-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0009_alter_student_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='impromptu_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField()),
                ('question2', models.CharField()),
                ('question3', models.CharField()),
            ],
        ),
    ]
